/* =============================================================================
   The Dopamine Dress-Up Den: the valet stand, the rails, and the copy slip.

   EVERYTHING IS READ OFF THE PAGE. Every garment's cut, every print's tile,
   every colourway's inks and every phrase the readout is made of are in the
   markup, generated by tools/make-dressup.py out of data/dressup.json; this
   file keeps no second copy of any of it. Add a garment to the data file and it
   is on the rails, on the stand and in the readout without this file changing.

   IT KEEPS NOTHING AND SENDS NOTHING. No storage, no request, no form action.
   The copy button puts a plain-text list on the visitor's own clipboard and the
   visitor decides where it goes. Closing the page empties the stand. It never
   reads the dial either: no garment is behind an intensity, and the sequins are
   on the rail at Gentle. make-dressup.py reads this file and refuses all three.

   NOBODY'S BODY IS DRAWN. The stand is a knob, two bars and a base, and the
   cuts are cloth and nothing else. A slot left as "your own" draws nothing,
   because what you have on is not ours to draw.

   A PRINT IS ONE <pattern> PER SLOT, and the colourway rides on it as custom
   properties that its tile's children inherit: --c1 to --c6 the inks cycled,
   --g the ground and --f1 to --f5 the figures. love.css fills each slot's cloth
   with that slot's pattern. Nothing here writes a colour.

   NOTHING MOVES AT GENTLE OR REGULAR. The rainbows on the wall drift at MAX, in
   love.css, with a translate, because rotation and skew are all check-gentle.py
   can read. Changing the outfit swaps the drawing at once: an outfit that slid
   into place would be motion nobody asked for.

   AN ARIA-LIVE REGION DOES NOT ANNOUNCE TEXT IT ALREADY HOLDS, and pressing
   Surprise me twice can land on the same words, so say() clears the region and
   sets it back on the next tick -- love.js's fix, which it does not export,
   repeated here as vital.js repeats it. Picking a garment is NOT announced: a
   screen reader already says the choice is checked, and the readout under the
   stand says the whole outfit for anybody who wants it.
   ============================================================================= */
(function () {
  'use strict';

  var form = document.getElementById('dd-rails');
  var stand = document.getElementById('dd-stand');
  var tpl = document.getElementById('dd-cuts');
  if (!form || !stand || !tpl) return;

  var readout = document.getElementById('dd-readout');
  var said = document.getElementById('dd-said');
  var fallback = document.getElementById('dd-fallback');
  var fallbackLab = document.querySelector('label.dd-fallback');

  var CUT = {}, PRINT = {};
  Array.prototype.forEach.call(tpl.content.querySelectorAll('[data-cut]'), function (g) {
    CUT[g.getAttribute('data-cut')] = g;
  });
  Array.prototype.forEach.call(tpl.content.querySelectorAll('[data-print]'), function (g) {
    PRINT[g.getAttribute('data-print')] = g;
  });

  function say(text) {
    said.textContent = '';
    setTimeout(function () { said.textContent = text; }, 60);
  }

  function inkVars(inks) {
    var n = inks.length, rest = inks.length > 1 ? inks.slice(1) : inks, out = [], i;
    out.push('--g:var(--dd-f-' + inks[0] + ')');
    for (i = 0; i < 6; i++) out.push('--c' + (i + 1) + ':var(--dd-f-' + inks[i % n] + ')');
    for (i = 0; i < 5; i++) out.push('--f' + (i + 1) + ':var(--dd-f-' + rest[i % rest.length] + ')');
    return out.join(';');
  }

  /* ── Reading the rails ─────────────────────────────────────────────────── */
  function cloth(box) {
    var p = box.querySelector('[data-part="print"]');
    var c = box.querySelector('[data-part="colours"]');
    var po = p.options[p.selectedIndex], co = c.options[c.selectedIndex];
    return {
      print: p.value, printA: po.getAttribute('data-a'),
      colours: c.value, colourName: co.textContent, first: co.getAttribute('data-first'),
      inks: co.getAttribute('data-inks').split('|')
    };
  }

  function worn() {
    var out = [];
    Array.prototype.forEach.call(form.querySelectorAll('.dd-rail[data-slot]'), function (rail) {
      var slot = rail.getAttribute('data-slot');
      if (slot === 'extras') return;
      var r = rail.querySelector('input[type="radio"]:checked');
      var piece = cloth(rail.querySelector('.dd-cloth'));
      piece.slot = slot;
      piece.label = rail.querySelector('legend').textContent;
      piece.garment = r && r.value !== 'own' ? r.value : null;
      piece.a = r ? r.getAttribute('data-a') : '';
      out.push(piece);
    });
    Array.prototype.forEach.call(form.querySelectorAll('.dd-extra'), function (box) {
      var cb = box.querySelector('input[type="checkbox"]');
      var piece = cloth(box.querySelector('.dd-cloth'));
      piece.slot = box.getAttribute('data-extra');
      piece.label = 'And';
      piece.garment = cb.checked ? cb.value : null;
      piece.a = cb.getAttribute('data-a');
      out.push(piece);
    });
    return out;
  }

  function phrase(p) {
    if (p.print === 'solid') return p.a + ' in plain ' + p.first;
    return p.a + ' ' + p.printA + ', ' + p.colourName;
  }

  /* ── Drawing the stand ─────────────────────────────────────────────────── */
  function draw(p) {
    var g = stand.querySelector('.dd-slot--' + p.slot);
    var pat = document.getElementById('dd-p-' + p.slot);
    if (!g || !pat) return;
    while (g.firstChild) g.removeChild(g.firstChild);
    if (p.garment && CUT[p.garment]) {
      Array.prototype.forEach.call(CUT[p.garment].childNodes, function (n) {
        g.appendChild(n.cloneNode(true));
      });
    }
    var tile = PRINT[p.print];
    if (!tile) return;
    while (pat.firstChild) pat.removeChild(pat.firstChild);
    Array.prototype.forEach.call(tile.childNodes, function (n) { pat.appendChild(n.cloneNode(true)); });
    pat.setAttribute('width', tile.getAttribute('data-w'));
    pat.setAttribute('height', tile.getAttribute('data-h'));
    pat.setAttribute('style', inkVars(p.inks));
  }

  function words(pieces) {
    var parts = pieces.filter(function (p) { return p.garment; }).map(phrase);
    if (!parts.length) return 'The stand is bare. Everything is whatever you have on.';
    if (parts.length > 1) parts[parts.length - 1] = 'and ' + parts[parts.length - 1];
    return 'On the stand: ' + parts.join('; ') + '.';
  }

  function update() {
    var pieces = worn();
    pieces.forEach(draw);
    readout.textContent = words(pieces);
    return pieces;
  }

  /* ── Setting the rails from a look, at random, or bare ─────────────────── */
  function pick(box, part, value) {
    var s = box.querySelector('[data-part="' + part + '"]');
    if (s && value) s.value = value;
  }

  function set(slot, garment, print, colours) {
    var rail = form.querySelector('.dd-rail[data-slot="' + slot + '"]');
    if (rail) {
      var r = rail.querySelector('input[type="radio"][value="' + (garment || 'own') + '"]');
      if (r) r.checked = true;
      pick(rail, 'print', print); pick(rail, 'colours', colours);
      return;
    }
    var box = form.querySelector('.dd-extra[data-extra="' + slot + '"]');
    if (box) {
      box.querySelector('input[type="checkbox"]').checked = !!garment;
      pick(box, 'print', print); pick(box, 'colours', colours);
    }
  }

  function bare() {
    Array.prototype.forEach.call(form.querySelectorAll('.dd-rail[data-slot]'), function (rail) {
      if (rail.getAttribute('data-slot') !== 'extras') set(rail.getAttribute('data-slot'), null);
    });
    Array.prototype.forEach.call(form.querySelectorAll('.dd-extra'), function (box) {
      set(box.getAttribute('data-extra'), null);
    });
  }

  function any(list) { return list[Math.floor(Math.random() * list.length)]; }
  function values(sel) { return Array.prototype.map.call(sel.options, function (o) { return o.value; }); }

  function surprise() {
    Array.prototype.forEach.call(form.querySelectorAll('.dd-rail[data-slot]'), function (rail) {
      if (rail.getAttribute('data-slot') === 'extras') return;
      var radios = Array.prototype.slice.call(rail.querySelectorAll('input[type="radio"]'));
      var real = radios.filter(function (r) { return r.value !== 'own'; });
      (Math.random() < .12 ? radios[0] : any(real)).checked = true;
      var p = rail.querySelector('[data-part="print"]'), c = rail.querySelector('[data-part="colours"]');
      p.value = any(values(p)); c.value = any(values(c));
    });
    Array.prototype.forEach.call(form.querySelectorAll('.dd-extra'), function (box) {
      box.querySelector('input[type="checkbox"]').checked = Math.random() < .3;
      var p = box.querySelector('[data-part="print"]'), c = box.querySelector('[data-part="colours"]');
      p.value = any(values(p)); c.value = any(values(c));
    });
  }

  function putOn(code) {
    bare();
    code.split('|').forEach(function (bit) {
      var f = bit.split(':');
      if (f[0].charAt(0) === '+') set(f[0].slice(1), f[0].slice(1), f[1], f[2]);
      else set(f[0], f[1], f[2], f[3]);
    });
  }

  /* ── The copy slip ─────────────────────────────────────────────────────── */
  function slip(pieces) {
    var lines = ['Off the rails at the Dopamine Dress-Up Den, stimpunks.world', ''];
    pieces.forEach(function (p) { if (p.garment) lines.push(p.label + ': ' + phrase(p)); });
    if (lines.length === 2) lines.push('Nothing on the stand. Whatever you have on.');
    return lines.join('\n');
  }

  function copy() {
    var text = slip(worn());
    function hand() {
      fallback.value = text;
      fallback.hidden = false; fallbackLab.hidden = false;
      fallback.focus(); fallback.select();
      say('Your clipboard would not take it, so it is in the box below the buttons to copy by hand.');
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () {
        fallback.hidden = true; fallbackLab.hidden = true;
        say('Copied. What is on the stand is on your clipboard, one piece to a line.');
      }, hand);
    } else hand();
  }

  /* ── Wiring ────────────────────────────────────────────────────────────── */
  form.addEventListener('change', update);
  form.addEventListener('submit', function (e) { e.preventDefault(); });

  document.getElementById('dd-copy').addEventListener('click', copy);
  document.getElementById('dd-surprise').addEventListener('click', function () {
    surprise();
    say(update().some(function (p) { return p.garment; }) ? 'Surprise. ' + readout.textContent : readout.textContent);
  });
  document.getElementById('dd-bare').addEventListener('click', function () {
    bare(); update();
    say('The stand is bare. Everything is whatever you have on.');
  });
  Array.prototype.forEach.call(document.querySelectorAll('.dd-put'), function (b) {
    b.addEventListener('click', function () {
      putOn(b.getAttribute('data-look'));
      update();
      say(b.getAttribute('data-name') + ' is on the stand. ' + readout.textContent);
      document.getElementById('the-stand').scrollIntoView({ block: 'start' });
    });
  });

  /* Shipped hidden, so a page with scripts off shows no dead control. */
  Array.prototype.forEach.call(document.querySelectorAll('.dd-cloth, .dd-look__go'), function (el) {
    el.hidden = false;
  });
  document.getElementById('dd-do').hidden = false;
  update();
})();
