/* =============================================================================
   Vital Plant Living: the builder, the section of your bowl, and the ticket.

   EVERYTHING IS READ OFF THE PAGE. The pantry, every item's shape and ink, the
   flavour bases and what each one brings are all in the markup, generated by
   tools/make-vital.py out of data/vital.json; this file keeps no second copy of
   any of it. A second list in here would be a list that goes stale the day
   somebody adds a jar to the pantry -- the `_headers` shape this repository has
   met more times than it would like. Add an item to the data file and it is
   tickable, drawable and copyable without this file being touched.

   IT KEEPS NOTHING AND SENDS NOTHING. No storage, no request, no form action.
   The copy button puts a plain-text ticket on the visitor's own clipboard, and
   the visitor decides where it goes: a shopping list, a message, nowhere.
   Closing the page empties the bowl, and the house rules say so.

   EVERYTHING TOUCHES, AND THE DRAWING IS WHY. The bowl is drawn cut straight
   through the middle, so every layer sits on the one under it and the sauce
   runs down into whatever it lands on. That is the room's whole claim, and
   Samefood Cafe's inverted: there nothing on a plate touches anything.

   NOTHING MOVES AT GENTLE OR REGULAR. The steam over a full bowl rises only at
   MAX, and it moves with a translate in love.css, because rotation and skew in
   the computed matrix are all check-gentle.py can read. The drawing itself is
   the same at every setting: Gentle takes away the wobble, never the words, and
   never the picture of what you built.

   AN ARIA-LIVE REGION DOES NOT ANNOUNCE TEXT IT ALREADY HOLDS, and copying
   twice is an ordinary thing to do, so say() clears the region and sets it
   back on the next tick -- love.js's fix, which it does not export, repeated
   here rather than approximated. Ticking a box is NOT announced: a screen
   reader already says the box is checked, and hearing it twice is worse than
   hearing it once.
   ============================================================================= */
(function () {
  'use strict';

  var form = document.getElementById('vpl-builder');
  if (!form) return;

  var cut = document.getElementById('vpl-cut');
  var ticket = document.getElementById('vpl-ticket');
  var head = document.getElementById('vpl-ticket-head');
  var none = document.getElementById('vpl-ticket-none');
  var body = document.getElementById('vpl-ticket-body');
  var copyBtn = document.getElementById('vpl-copy');
  var clearBtn = document.getElementById('vpl-clear');
  var said = document.getElementById('vpl-said');
  var says = document.getElementById('vpl-says');
  var fallbackLab = document.querySelector('label.vpl-fallback');
  var fallback = document.getElementById('vpl-fallback');

  var ORDER = ['base', 'veg', 'aroma', 'sauce', 'fruit', 'top', 'texture', 'spice'];
  var WEIGHT = { base: 3, veg: 2, aroma: 1, sauce: 1.1, fruit: 1.4, top: 1.2, texture: .8, spice: .5 };
  var BASE_INKS = ['green', 'rice', 'orange', 'red', 'gold', 'plum'];
  var SIZE = {
    grain: [7, 4], strand: [26, 6], chunk: [14, 11], round: [12, 12], bean: [12, 8],
    leaf: [20, 10], slice: [18, 6], floret: [16, 16], pod: [22, 8], pea: [7, 7],
    shred: [16, 6], fleck: [6, 4], dust: [4, 3], seed: [5, 3], nut: [11, 8],
    ring: [11, 11], berry: [10, 10], wedge: [15, 10]
  };
  var SPECIAL = { sauce: 1, drizzle: 1, dollop: 1 };
  var LINE = ' stroke="var(--vpl-ink)" stroke-width="1.1" stroke-linejoin="round"';

  function ink(n) { return n === 'bowl' ? 'var(--vpl-bowl)' : 'var(--vpl-f-' + n + ')'; }
  function rnd(seed) { var x = Math.sin(seed * 12.9898 + 78.233) * 43758.5453; return x - Math.floor(x); }
  function r1(n) { return Math.round(n * 10) / 10; }

  /* ── The vessels, in section ───────────────────────────────────────────── */
  var VESSELS = {
    bowl: {
      clip: 'M34 96 Q34 246 200 254 Q366 246 366 96 Z',
      x0: 34, x1: 366, top: 100, bottom: 254,
      under: function (f) {
        return '<rect x="146" y="262" width="108" height="20" rx="6" fill="' + f + '"' + LINE + '/>';
      },
      over: function (f) {
        return '<path d="M14 96 Q14 264 200 272 Q386 264 386 96 L366 96 Q366 246 200 254 Q34 246 34 96 Z" fill="' + f +
          '" stroke="var(--vpl-ink)" stroke-width="2.2" stroke-linejoin="round"/>';
      }
    },
    roll: {
      clip: 'M200 34 A116 116 0 1 1 199.9 34 Z',
      x0: 84, x1: 316, top: 40, bottom: 266,
      under: function () { return ''; },
      over: function (f) {
        return '<path d="M200 22 A128 128 0 1 1 199.9 22 Z M200 34 A116 116 0 1 0 200.1 34 Z" fill="' + f +
          '" fill-rule="evenodd" stroke="var(--vpl-ink)" stroke-width="2.2"/>' +
          '<path d="M104 214 A112 112 0 0 1 132 70" fill="none" stroke="var(--vpl-ink)" stroke-width="11" stroke-linecap="round"/>' +
          '<path d="M104 214 A112 112 0 0 1 132 70" fill="none" stroke="' + f + '" stroke-width="7" stroke-linecap="round"/>';
      }
    },
    fold: {
      clip: 'M80 40 Q78 234 200 244 Q322 234 320 40 Z',
      x0: 80, x1: 320, top: 52, bottom: 244,
      under: function () { return ''; },
      over: function (f) {
        return '<path d="M62 40 Q58 256 200 266 Q342 256 338 40 L320 40 Q322 234 200 244 Q78 234 80 40 Z" fill="' + f +
          '" stroke="var(--vpl-ink)" stroke-width="2.2" stroke-linejoin="round"/>';
      }
    },
    stack: {
      clip: 'M44 70 H356 V232 H44 Z',
      x0: 44, x1: 356, top: 72, bottom: 232,
      under: function (f) {
        return '<rect x="30" y="232" width="340" height="40" rx="14" fill="' + f + '" stroke="var(--vpl-f-brown)" stroke-width="6"/>' +
          '<rect x="30" y="232" width="340" height="40" rx="14" fill="none" stroke="var(--vpl-ink)" stroke-width="1.6"/>';
      },
      over: function (f, filledTop) {
        var y = Math.max(28, Math.min(192, filledTop - 38));
        return '<rect x="30" y="' + r1(y) + '" width="340" height="40" rx="14" fill="' + f + '" stroke="var(--vpl-f-brown)" stroke-width="6"/>' +
          '<rect x="30" y="' + r1(y) + '" width="340" height="40" rx="14" fill="none" stroke="var(--vpl-ink)" stroke-width="1.6"/>';
      }
    }
  };

  /* ── The pieces ────────────────────────────────────────────────────────── */
  function piece(shape, fill, x, y, s) {
    var f = ' fill="' + fill + '"';
    var j = rnd(s) - .5;
    switch (shape) {
      case 'grain':  return '<ellipse cx="' + r1(x) + '" cy="' + r1(y) + '" rx="' + r1(3.4 + j) + '" ry="2"' + f + ' stroke="var(--vpl-ink)" stroke-width=".7"/>';
      case 'strand': return '<path d="M' + r1(x - 13) + ' ' + r1(y) + ' q6.5 ' + r1(-5 - j * 4) + ' 13 0 t13 0" fill="none" stroke="var(--vpl-ink)" stroke-width="5" stroke-linecap="round"/>' +
                            '<path d="M' + r1(x - 13) + ' ' + r1(y) + ' q6.5 ' + r1(-5 - j * 4) + ' 13 0 t13 0" fill="none" stroke="' + fill + '" stroke-width="3" stroke-linecap="round"/>';
      case 'chunk':  return '<rect x="' + r1(x - 7) + '" y="' + r1(y - 5.5) + '" width="' + r1(13 + j * 3) + '" height="11" rx="3"' + f + LINE + '/>';
      case 'round':  return '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="' + r1(5.6 + j) + '"' + f + LINE + '/>';
      case 'bean':   return '<ellipse cx="' + r1(x) + '" cy="' + r1(y) + '" rx="5.8" ry="' + r1(3.8 + j * .6) + '"' + f + LINE + '/>';
      case 'leaf':   return '<path d="M' + r1(x - 10) + ' ' + r1(y) + ' Q' + r1(x) + ' ' + r1(y - 9 - j * 4) + ' ' + r1(x + 10) + ' ' + r1(y) + ' Q' + r1(x) + ' ' + r1(y + 6) + ' ' + r1(x - 10) + ' ' + r1(y) + ' Z"' + f + LINE + '/>';
      case 'slice':  return '<rect x="' + r1(x - 9) + '" y="' + r1(y - 3) + '" width="18" height="' + r1(5 + j) + '" rx="2.5"' + f + LINE + '/>';
      case 'floret': return '<path d="M' + r1(x) + ' ' + r1(y + 7) + ' V' + r1(y) + '" stroke="var(--vpl-ink)" stroke-width="4"/>' +
                            '<circle cx="' + r1(x - 4) + '" cy="' + r1(y - 2) + '" r="4.6"' + f + LINE + '/><circle cx="' + r1(x + 4) + '" cy="' + r1(y - 2) + '" r="4.6"' + f + LINE + '/><circle cx="' + r1(x) + '" cy="' + r1(y - 6) + '" r="4.6"' + f + LINE + '/>';
      case 'pod':    return '<path d="M' + r1(x - 11) + ' ' + r1(y) + ' Q' + r1(x) + ' ' + r1(y - 8) + ' ' + r1(x + 11) + ' ' + r1(y) + ' Q' + r1(x) + ' ' + r1(y + 7) + ' ' + r1(x - 11) + ' ' + r1(y) + ' Z"' + f + LINE + '/>' +
                            '<circle cx="' + r1(x - 4) + '" cy="' + r1(y) + '" r="1.6" fill="var(--vpl-ink)"/><circle cx="' + r1(x + 3) + '" cy="' + r1(y) + '" r="1.6" fill="var(--vpl-ink)"/>';
      case 'pea':    return '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="3.4"' + f + ' stroke="var(--vpl-ink)" stroke-width=".9"/>';
      case 'shred':  return '<path d="M' + r1(x - 8) + ' ' + r1(y + 1) + ' q4 ' + r1(-4 + j * 3) + ' 8 -1 t8 0" fill="none" stroke="var(--vpl-ink)" stroke-width="4.2" stroke-linecap="round"/>' +
                            '<path d="M' + r1(x - 8) + ' ' + r1(y + 1) + ' q4 ' + r1(-4 + j * 3) + ' 8 -1 t8 0" fill="none" stroke="' + fill + '" stroke-width="2.4" stroke-linecap="round"/>';
      case 'fleck':  return '<path d="M' + r1(x - 3) + ' ' + r1(y + 2) + ' L' + r1(x + j * 2) + ' ' + r1(y - 2.5) + ' L' + r1(x + 3) + ' ' + r1(y + 2) + ' Z"' + f + ' stroke="var(--vpl-ink)" stroke-width=".7"/>';
      case 'dust':   return '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="1.5"' + f + ' stroke="var(--vpl-ink)" stroke-width=".5"/>';
      case 'seed':   return '<ellipse cx="' + r1(x) + '" cy="' + r1(y) + '" rx="2.4" ry="1.5"' + f + ' stroke="var(--vpl-ink)" stroke-width=".6"/>';
      case 'nut':    return '<path d="M' + r1(x - 5) + ' ' + r1(y + 3) + ' Q' + r1(x - 5) + ' ' + r1(y - 5) + ' ' + r1(x) + ' ' + r1(y - 4) + ' Q' + r1(x + 6) + ' ' + r1(y - 4) + ' ' + r1(x + 5) + ' ' + r1(y + 3) + ' Z"' + f + LINE + '/>';
      case 'ring':   return '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="4.4" fill="none" stroke="var(--vpl-ink)" stroke-width="4"/>' +
                            '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="4.4" fill="none" stroke="' + fill + '" stroke-width="2.2"/>';
      case 'berry':  return '<circle cx="' + r1(x) + '" cy="' + r1(y) + '" r="4.8"' + f + LINE + '/><circle cx="' + r1(x - 1.6) + '" cy="' + r1(y - 1.6) + '" r="1.1" fill="var(--vpl-f-rice)"/>';
      case 'wedge':  return '<path d="M' + r1(x - 7) + ' ' + r1(y + 4) + ' A7 7 0 0 1 ' + r1(x + 7) + ' ' + r1(y + 4) + ' Z"' + f + LINE + '/>';
    }
    return '';
  }

  /* A band of one layer's pieces, filled in rows from the bottom of the band.
     The pieces take turns across each row, so a band of rice and beans comes
     out as rice and beans rather than as a stripe of each. */
  function band(things, x0, x1, yb, h, seed) {
    var solid = things.filter(function (t) { return !SPECIAL[t.shape]; });
    var out = '';
    if (solid.length) {
      var w = 0, rh = 0;
      solid.forEach(function (t) { var sz = SIZE[t.shape] || [10, 8]; w = Math.max(w, sz[0]); rh = Math.max(rh, sz[1]); });
      w += 3; rh += 1.5;
      var rows = Math.max(1, Math.floor(h / rh));
      var cols = Math.max(1, Math.floor((x1 - x0) / w));
      var k = 0;
      for (var r = 0; r < rows; r++) {
        var y = yb - rh * (r + .5);
        var off = (r % 2) * w / 2;
        for (var c = 0; c < cols + 1; c++) {
          var t = solid[(c + r * 2) % solid.length];
          var s = seed + r * 31 + c * 7;
          var x = x0 + off + c * w + (rnd(s) - .5) * w * .35;
          out += piece(t.shape, ink(t.ink), x, y + (rnd(s + 3) - .5) * rh * .4, s);
          k++;
        }
      }
    }
    // Sauces last, over what they landed on, and they run down into it.
    var wet = things.filter(function (t) { return SPECIAL[t.shape]; });
    wet.forEach(function (t, i) {
      var f = ink(t.ink), yy = yb - h + (h / Math.max(1, wet.length)) * i;
      var hh = h / Math.max(1, wet.length);
      var sd = seed + i * 53;
      if (t.shape === 'sauce') {
        var d = 'M' + x0 + ' ' + r1(yy + hh);
        for (var x = x0; x <= x1; x += 20) d += ' L' + x + ' ' + r1(yy + hh * .15 + (rnd(sd + x) - .5) * 6);
        d += ' L' + x1 + ' ' + r1(yy + hh) + ' Z';
        out += '<path class="vpl-wet" d="' + d + '" fill="' + f + '"' + LINE + '/>';
        for (var dx = x0 + 30; dx < x1 - 20; dx += 58) {
          var dl = 10 + rnd(sd + dx) * 22;
          out += '<path class="vpl-wet" d="M' + r1(dx - 4) + ' ' + r1(yy + hh - 1) + ' q0 ' + r1(dl) + ' 4 ' + r1(dl) + ' q4 0 4 ' + r1(-dl) + ' Z" fill="' + f + '"' + LINE + '/>';
        }
      } else if (t.shape === 'drizzle') {
        var p = 'M' + x0 + ' ' + r1(yy + hh * .5);
        for (var q = x0 + 16; q <= x1; q += 16) p += ' Q' + r1(q - 8) + ' ' + r1(yy + hh * .5 + (q % 32 ? -7 : 7)) + ' ' + q + ' ' + r1(yy + hh * .5);
        out += '<path class="vpl-wet" d="' + p + '" fill="none" stroke="var(--vpl-ink)" stroke-width="5.4" stroke-linecap="round"/>' +
               '<path class="vpl-wet" d="' + p + '" fill="none" stroke="' + f + '" stroke-width="3.4" stroke-linecap="round"/>';
        for (var ex = x0 + 44; ex < x1 - 20; ex += 70) {
          var el = 8 + rnd(sd + ex) * 16;
          out += '<path class="vpl-wet" d="M' + ex + ' ' + r1(yy + hh * .5) + ' v' + r1(el) + '" stroke="var(--vpl-ink)" stroke-width="4" stroke-linecap="round"/>' +
                 '<path class="vpl-wet" d="M' + ex + ' ' + r1(yy + hh * .5) + ' v' + r1(el) + '" stroke="' + f + '" stroke-width="2.2" stroke-linecap="round"/>';
        }
      } else {
        for (var mx = x0 + 44 + i * 26; mx < x1 - 30; mx += 104) {
          out += '<path class="vpl-wet" d="M' + r1(mx - 24) + ' ' + r1(yy + hh) + ' Q' + r1(mx - 22) + ' ' + r1(yy - 4) + ' ' + r1(mx) + ' ' + r1(yy - 6) +
                 ' Q' + r1(mx + 22) + ' ' + r1(yy - 4) + ' ' + r1(mx + 24) + ' ' + r1(yy + hh) + ' Z" fill="' + f + '"' + LINE + '/>';
        }
      }
    });
    return out;
  }

  var clipN = 0;
  function draw(svg, sel) {
    var v = VESSELS[sel.form] || VESSELS.bowl;
    var id = 'vpl-clip-' + (++clipN);
    var layers = {};
    sel.things.forEach(function (t) { (layers[t.layer] = layers[t.layer] || []).push(t); });
    var present = ORDER.filter(function (l) { return layers[l]; });
    var depth = v.bottom - v.top;
    var full = depth * Math.min(.96, .4 + .05 * sel.things.length);
    var sum = present.reduce(function (a, l) { return a + WEIGHT[l]; }, 0) || 1;
    var y = v.bottom, inner = '';
    present.forEach(function (l, i) {
      var h = full * WEIGHT[l] / sum;
      inner += band(layers[l], v.x0, v.x1, y, h, (i + 1) * 101);
      y -= h;
    });
    var out = '<defs><clipPath id="' + id + '"><path d="' + v.clip + '"/></clipPath></defs>' +
      v.under(ink(sel.ink)) +
      '<g clip-path="url(#' + id + ')">' + inner + '</g>' +
      v.over(ink(sel.ink), y);
    if (sel.things.length) {
      out += '<g class="vpl-steam">';
      for (var s = 0; s < 3; s++) {
        var sx = 150 + s * 50;
        out += '<path d="M' + sx + ' ' + r1(Math.max(12, y - 8)) + ' q-10 -14 0 -26 t0 -26" fill="none" stroke="var(--vpl-ink-2)" stroke-width="2.4" stroke-linecap="round" opacity=".55"/>';
      }
      out += '</g>';
    }
    svg.innerHTML = out;
    svg.removeAttribute("hidden");
  }

  /* ── Reading the page ──────────────────────────────────────────────────── */
  function look(input) {
    return { shape: input.dataset.shape, ink: input.dataset.ink, layer: input.dataset.layer };
  }
  function labelOf(input) {
    var n = input.closest('label').querySelector('.vpl-chip__name');
    return (n.firstChild && n.firstChild.nodeType === 3 ? n.firstChild.nodeValue : n.textContent).trim();
  }
  function baseThings(key, brings, i) {
    return brings.split('|').map(function (b, k) {
      return { shape: 'fleck', ink: BASE_INKS[(i + k) % BASE_INKS.length], layer: 'aroma' };
    });
  }

  function selection() {
    var vessel = form.querySelector('input[name="vpl-vessel"]:checked');
    var sel = { form: vessel.dataset.form, ink: vessel.dataset.ink, vessel: vessel, things: [] };
    form.querySelectorAll('input[name="vpl-base"]:checked').forEach(function (b, i) {
      sel.things = sel.things.concat(baseThings(b.value, b.dataset.brings, i));
    });
    form.querySelectorAll('input[name="vpl-item"]:checked').forEach(function (c) { sel.things.push(look(c)); });
    return sel;
  }

  /* The groups, in the order the builder shows them, each with the name its
     own legend gives it -- read off the page, so the ticket's headings are the
     pantry's own section names and cannot drift from them. */
  function groups() {
    var out = [];
    var v = form.querySelector('input[name="vpl-vessel"]:checked');
    if (v.value !== 'bowl') out.push({ name: 'Wrap', items: [labelOf(v)] });
    form.querySelectorAll('.vpl-group').forEach(function (g) {
      if (g.classList.contains('vpl-group--vessel')) return;
      var name = g.querySelector('legend').textContent.trim();
      var items = [];
      g.querySelectorAll('input:checked').forEach(function (c) {
        items.push(c.name === 'vpl-base'
          ? labelOf(c) + ': ' + c.dataset.brings.split('|').join(', ')
          : labelOf(c));
      });
      if (items.length) out.push({ name: name, items: items });
    });
    return out;
  }

  function what() {
    var v = form.querySelector('input[name="vpl-vessel"]:checked');
    return v.value === 'bowl' ? 'bowl' : 'wrap';
  }

  function render() {
    var sel = selection();
    draw(cut, sel);
    var gs = groups();
    var v = sel.vessel;
    head.textContent = v.value === 'bowl' ? 'A bowl' : 'A wrap, in ' + labelOf(v).toLowerCase();
    body.textContent = '';
    var filled = gs.filter(function (g) { return g.name !== 'Wrap'; });
    none.hidden = filled.length > 0;
    filled.forEach(function (g) {
      var dt = document.createElement('dt'), dd = document.createElement('dd');
      dt.textContent = g.name;
      dd.textContent = g.items.join(', ');
      body.appendChild(dt); body.appendChild(dd);
    });
    copyBtn.textContent = 'Copy your ' + what() + ' to the clipboard';
    ticket.hidden = false;
  }

  function ticketText() {
    var gs = groups();
    var v = form.querySelector('input[name="vpl-vessel"]:checked');
    var lines = [(v.value === 'bowl' ? 'A bowl' : 'A wrap, in ' + labelOf(v).toLowerCase()) + ', from Vital Plant Living'];
    gs.forEach(function (g) {
      lines.push('', g.name);
      g.items.forEach(function (i) { lines.push('- ' + i); });
    });
    lines.push('', 'Built at ' + location.origin + location.pathname);
    return lines.join('\n');
  }

  /* ── Saying so, where the hand is ──────────────────────────────────────── */
  var cards = document.querySelectorAll('.vpl-combo__said');
  function quiet() {
    said.hidden = true; said.textContent = '';
    cards.forEach(function (c) { c.hidden = true; c.textContent = ''; });
  }
  function say(text) {
    says.textContent = '';
    setTimeout(function () { says.textContent = text; }, 60);
  }
  function answer(text) {
    quiet();
    said.textContent = text;
    said.hidden = false;
    say(text);
  }

  form.addEventListener('submit', function (e) { e.preventDefault(); });
  form.addEventListener('change', function () {
    quiet();
    fallback.hidden = true; fallbackLab.hidden = true;
    render();
  });

  copyBtn.addEventListener('click', function () {
    var text = ticketText();
    var noun = what();
    function fallbackCopy() {
      fallback.value = text;
      fallback.hidden = false; fallbackLab.hidden = false;
      fallback.focus(); fallback.select();
      answer('Could not reach the clipboard. Your ' + noun + ' is in the box below, selected, ready to copy by hand.');
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () {
        fallback.hidden = true; fallbackLab.hidden = true;
        answer('Copied your ' + noun + '. Paste it wherever you keep your shopping list.');
      }, fallbackCopy);
    } else {
      fallbackCopy();
    }
  });

  clearBtn.addEventListener('click', function () {
    form.reset();
    fallback.hidden = true; fallbackLab.hidden = true;
    render();
    answer('Emptied. It is a bowl again, with nothing in it.');
  });

  /* ── The board ─────────────────────────────────────────────────────────── */
  function comboSel(btn) {
    var vessel = document.getElementById('vpl-vessel-' + btn.dataset.vessel);
    var sel = { form: vessel.dataset.form, ink: vessel.dataset.ink, things: [] };
    btn.dataset.bases.split('|').forEach(function (k, i) {
      var b = document.getElementById('vpl-base-' + k);
      if (b) sel.things = sel.things.concat(baseThings(k, b.dataset.brings, i));
    });
    btn.dataset.items.split('|').forEach(function (s) {
      var c = document.getElementById('vpl-item-' + s);
      if (c) sel.things.push(look(c));
    });
    return sel;
  }

  document.querySelectorAll('.vpl-load').forEach(function (btn) {
    var card = btn.closest('.vpl-combo');
    var mini = card.querySelector('.vpl-cut--mini');
    var out = card.querySelector('.vpl-combo__said');
    draw(mini, comboSel(btn));
    btn.parentNode.hidden = false;
    btn.addEventListener('click', function () {
      form.reset();
      document.getElementById('vpl-vessel-' + btn.dataset.vessel).checked = true;
      btn.dataset.bases.split('|').forEach(function (k) {
        var b = document.getElementById('vpl-base-' + k); if (b) b.checked = true;
      });
      btn.dataset.items.split('|').forEach(function (s) {
        var c = document.getElementById('vpl-item-' + s); if (c) c.checked = true;
      });
      fallback.hidden = true; fallbackLab.hidden = true;
      render();
      quiet();
      var text = btn.dataset.name + ' is in the builder now, in place of whatever was in there. Change anything you like, then copy it.';
      out.textContent = text + ' ';
      var a = document.createElement('a');
      a.href = '#vpl-pass';
      a.textContent = 'See it in the builder ↑';
      out.appendChild(a);
      out.hidden = false;
      say(text);
    });
  });

  render();
})();
