/* The Zibaldone's attribution slip.

   IT SENDS NOTHING ANYWHERE, and that is a design decision rather than a
   limitation. There is no form action, no endpoint, no fetch and no storage in
   this file: the button assembles the text and puts it on the clipboard, and
   the person decides where it goes. A room that collected other people's
   submissions would be asking our community to hand their words to a server
   nobody on this street has told them about -- which is the same consent this
   site spends a whole mechanism protecting one room over, arriving as a form.

   IT READS THE FIELDS OFF THE PAGE RATHER THAN LISTING THEM AGAIN. The slip's
   fields are generated by tools/make-zibaldone.py out of the same list the
   cards are checked against, so a second copy of that list in here is a copy
   that goes stale the day somebody adds a field -- the `_headers` shape this
   repository has now met more times than it would like. Every control inside
   the form is picked up by its own name and its own label. Add a field to the
   tool and it appears in the copied text without this file being touched.

   THE READOUT SAYS THE SAME THING TWICE ON PURPOSE. Pressing copy twice is an
   ordinary thing to do, and an aria-live region does not announce text it
   already holds -- so the second press would be silent for the one reader who
   most needs to hear it, while looking perfectly correct on screen. love.js
   carries the clear-and-set-back fix for exactly this and does not export it,
   so it is repeated here rather than approximated. */
(function () {
  'use strict';

  var form = document.getElementById('zb-slip');
  var copy = document.getElementById('zb-copy');
  var said = document.getElementById('zb-said');
  var out = document.getElementById('zb-out');
  var box = document.getElementById('zb-outbox');
  if (!form || !copy || !said || !out || !box) return;

  /* Both ship hidden so a page with no JavaScript shows no dead control and no
     empty box. §2's [hidden] guard carries !important, which is the only
     reason that holds against a room's own display rules. */
  copy.hidden = false;
  out.hidden = false;

  function labelFor(el) {
    var l = form.querySelector('label[for="' + el.id + '"]');
    if (!l) return el.name;
    /* The label carries a "needed" flag and the TASL key as spans; neither is
       part of what the field is called, so they come off before it is used. */
    var clone = l.cloneNode(true);
    Array.prototype.forEach.call(clone.querySelectorAll('.zb-slip__req, .zb-slip__key'),
      function (s) { s.remove(); });
    return clone.textContent.replace(/\s+/g, ' ').trim();
  }

  function fields() {
    return Array.prototype.slice.call(form.querySelectorAll('input[name], textarea[name]'));
  }

  function compose() {
    var lines = ['A quote for the Zibaldone', ''];
    var any = false;
    fields().forEach(function (el) {
      var v = el.value.replace(/\s+$/, '');
      if (!v) return;
      any = true;
      lines.push(labelFor(el) + ':');
      v.split('\n').forEach(function (line) { lines.push('  ' + line); });
      lines.push('');
    });
    if (!any) return '';
    lines.push('Sent from the attribution slip at https://stimpunks.love/zibaldone.html');
    return lines.join('\n').replace(/\n{3,}/g, '\n\n');
  }

  function speak(text) {
    if (said.textContent === text) {
      said.textContent = '';
      window.setTimeout(function () { said.textContent = text; }, 60);
    } else {
      said.textContent = text;
    }
  }

  function refresh() {
    var text = compose();
    box.value = text;
    /* An empty slip would copy an empty string and say it had worked, which is
       a control that gives no sign of having done nothing. */
    copy.disabled = !text;
  }

  form.addEventListener('input', refresh);
  refresh();

  copy.addEventListener('click', function () {
    var text = box.value;
    if (!text) { speak('Nothing filled in yet, so there is nothing to copy.'); return; }

    function fallback() {
      /* Selecting the box means somebody can finish the job by hand with one
         keystroke, which is a better failure than a button that did nothing. */
      box.focus();
      box.select();
      speak('Could not reach the clipboard. The slip is selected in the box below — copy it from there.');
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function () {
        speak('Copied. Paste it into an email, a message, or wherever you talk to us.');
      }, fallback);
    } else {
      fallback();
    }
  });
})();
