#!/usr/bin/env python3
"""Build Swaying Sweetgrass — the meadow, the fire pit, the braid — from data/sweetgrass.json.

ONE DATA FILE, ONE TOOL, BOTH SURFACES. The room and its credits in liner-notes
move together, which is the contract make-yells.py has and every generator here
has copied since.

IT HOLDS THE RUNTIME RULE THE ORDINARY WAY and one refusal no other tool here
has, which is the reason this file is worth reading before editing the room.

  · A RECORDING AT THE FIRE, IN THE FIELD GUIDE OR BESIDE THE BOOK NEEDS A
    RUNTIME. Same promise as make-latibulum.py, make-den.py, make-club.py and
    the Hermitage's campfire: the number is what lets somebody decide before
    they press.

  · THE BOOK IS LENT AND PREVIEWED, NEVER SERVED. This is the room's own
    refusal and it exists to keep a decision from being quietly reversed.
    Braiding Sweetgrass is in copyright: Milkweed Editions, 2013, its author
    living and publishing. From 2026-09-21 the room listed an unauthorised
    chapter-by-chapter reading of it as doors out, because every one of them
    played and embedded and NOTHING ELSE WOULD HAVE STOPPED THEM going in as
    screens -- not love-embed.js, which only asks whether an id is well formed,
    and not check-jukebox.py, which only asks whether a video works. The room's
    whole argument is the honorable harvest: never take the first, never take
    more than you need, ask. A page making that argument cannot serve somebody
    else's entire book off its own surface. YouTube stopped serving those
    readings by 2026-10-08, and Ryan had them taken off quietly on 2026-10-10,
    with nothing on the page saying they were there (DECISIONS.md). What sits
    beside the book now is one press, Google Play Books' own preview of the
    authorised audiobook, which Kimmerer narrates, with the borrow link beside it.

    So this REFUSES A `readings` LIST AND ANYTHING ON _refused_channel, at the
    fire, in the field guide, beside the book or as the fire itself. The
    friendly edit is a real one and it will arrive: somebody finds the book read
    aloud again, somewhere else, and puts it back because the preview stops
    partway. The channel was also the only thing that ever told those
    readings apart from the talks: they arrived in one brief looking identical.

  · AND THE FIRE ITSELF IS THE ONE THING HERE THAT MAY NOT HAVE A RUNTIME.
    Ryan's brief, 2026-09-28: the pit had talks round it and no fire in it. The
    fire is a whole playlist of campfires, put on and left burning, so this
    tool holds make-club.py's pair at once -- a runtime REQUIRED on every
    recording and REFUSED on the list, because a list its channel keeps adding
    to has no length and today's total is wrong next week. It also refuses a
    list that does not say what it OPENS on (Queercore's lesson: position 1
    decides whether the whole list embeds), and our note saying what a fire is
    FOR. Those videos are sold for sleep and focus, and this room says out loud
    that it does not treat a meadow as a treatment.

  · AND THE FIRES IN THE PLAYLIST ARE A RACK UNDER IT, rack.js's pattern. Each
    is one recording, so each needs a runtime; each is on the playlist's
    channel; and the notes are swept like the fire's. The Campfire at Cavendish
    Coworking reads this list by key, so a fire changed here changes there.

  · THE BRAID IS THREE BUNDLES OF SEVEN AND THE TOOL COUNTS THEM. Seven behind,
    seven laws, seven ahead, twenty-one in the braid. That is somebody's
    teaching rather than a layout, and a bundle that lost a strand to an edit
    would be this page getting an Elder's words wrong in the one place a reader
    would assume we had been careful. It is the opposite of check-counts.py's
    rule and for the opposite reason: a count that belongs to somebody else is
    a fact to protect, not a total that goes stale.

  · VIDEOPRESS IS THE THIRD ORIGIN ON THIS STREET, and this file no longer
    keeps its own copy of the list. love-embed.js's ORIGINS array is the single
    source of truth: the script enforces it at runtime, make-csp.py derives
    frame-src from it, and this reads it to refuse a bad URL at build time --
    the only one of the three that catches it before anybody sees a blank box.

    IT WAS THREE HAND-KEPT COPIES AND THAT IS EXACTLY HOW IT BROKE. videopress
    was added to _headers by hand, which looked right and was confirmed in the
    file -- but that line is GENERATED by make-csp.py from a literal of its own,
    so every later run put the old list back. The dev server serves no headers,
    so the room worked locally and the live site refused the frame.

IF THIS REFUSES: fix the data. Do not loosen the tool.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "sweetgrass.json"
ROOM = ROOT / "swaying-sweetgrass.html"
NOTES = ROOT / "liner-notes.html"

YT = re.compile(r"^[A-Za-z0-9_-]{11}$")
# What the fire's own titles sell it for. Our note says what is in the picture
# and what you hear, never what it will do for you.
FOR = re.compile(r"\b(sleep\w*|relax\w*|focus\w*|calm\w*|soothe?s?|soothing|stress\w*|"
                 r"anxi\w*|insomnia|therap\w*|heal\w*|asmr|meditat\w*|productiv\w*)\b", re.I)
CLOCK = re.compile(r"^\d{1,2}:\d{2}(:\d{2})?$")

def framed_origins():
    """The origins this site will build a frame for, READ OUT OF love-embed.js.

    It used to be a literal list here, which made a third hand-maintained copy
    of something that has to agree in three places -- and the copies did not
    agree: videopress.com was added to _headers by hand, that line is GENERATED
    by make-csp.py, and every later run put the old list back. The room worked
    on the dev server, which serves no headers, and the live site refused the
    frame. So love-embed.js is the single source and make-csp.py reads the same
    array for the same reason. Adding a service means editing that array."""
    js = (ROOT / "love-embed.js").read_text()
    block = re.search(r"var ORIGINS = \[(.*?)\];", js, re.S)
    if not block:
        raise SystemExit(
            "REFUSING: love-embed.js has no ORIGINS array, so this tool cannot tell\n"
            "whether the room's video points somewhere this site will actually frame.")
    return tuple(re.findall(r"'(https://[^']+)'", block.group(1)))


def esc(s):
    return html.escape(s, quote=False)


def swap(page, marker, block, indent=""):
    begin, end = f"<!-- {marker}:begin -->", f"<!-- {marker}:end -->"
    src = page.read_text()
    if begin not in src or end not in src:
        raise SystemExit(
            f"REFUSING: {page.name} has no {marker} markers, so there is nowhere\n"
            "to write. Add them on purpose rather than letting this tool render nothing.")
    page.write_text(re.sub(re.escape(begin) + r".*?" + re.escape(end),
                           lambda m: begin + "\n" + block + "\n" + indent + end,
                           src, flags=re.S))


def check(d):
    bad = []
    fire, teach = d.get("fire") or [], d.get("teachings") or []
    pv = (d.get("book") or {}).get("preview")
    preview = [pv] if pv else []
    if not fire:
        bad.append("no recordings at the fire, and the fire pit is what the clearing is for.")
    if not teach:
        bad.append("no teachings, and the field guide is not ours to write without them.")
    if not preview:
        bad.append("no preview beside the book. The one recording of the book on the page is "
                   "the authorised audiobook's preview, with the borrow link beside it.")

    # The rights refusal. See the docstring.
    if "readings" in d:
        bad.append("a `readings` list is back. The chapter readings came off on 2026-10-10 and the "
                   "book is lent and previewed, never served; see this tool's docstring and "
                   "DECISIONS.md before changing it.")
    walled = (d.get("_refused_channel") or "").strip()
    if not walled:
        bad.append("_refused_channel is empty, so the refusal below cannot run at all.")

    seen = {}
    for label, rows in (("the fire", fire), ("the field guide", teach), ("the preview", preview)):
        for r in rows:
            t = (r.get("title") or "").strip() or "<untitled>"
            i = (r.get("id") or "").strip()
            if not YT.match(i):
                bad.append(f"{label}: {t!r} has {i!r}, which is not a YouTube id. "
                           "love-embed.js refuses it quietly at runtime, which is a "
                           "button somebody presses and presses.")
            if i in seen:
                bad.append(f"{label}: {t!r} is the same video as {seen[i]!r}.")
            seen[i] = t
            if not CLOCK.match((r.get("length") or "").strip()):
                bad.append(f"{label}: {t!r} has no runtime. Every press-to-play label on "
                           "this street says how long before the press.")
            if not (r.get("spoken") or "").strip():
                bad.append(f"{label}: {t!r} has no spoken runtime for the button.")

    for label, rows in (("the fire", fire), ("the field guide", teach), ("the preview", preview)):
        for r in rows:
            if walled and (r.get("channel") or "").strip() == walled:
                bad.append(
                    f"{label}: {r.get('title')!r} is on {walled!r}, whose unauthorised reading "
                    "of the book came off this page on 2026-10-10. Nothing from it goes back.")
            if r.get("how") != "screen":
                bad.append(f"{label}: {r.get('title')!r} is marked {r.get('how')!r}; "
                           "everything at the fire and in the guide is a screen.")
            if not (r.get("channel") or "").strip():
                bad.append(f"{label}: {r.get('title')!r} names no channel, and this room "
                           "credits the channel on every row.")
            if not (r.get("note") or "").strip():
                bad.append(f"{label}: {r.get('title')!r} has no note saying what it is.")

    # The fire itself: a playlist, so the runtime rule turns over.
    h = d.get("hearth") or {}
    if not h:
        bad.append("no fire in the fire pit. The hearth is a playlist of real fires and the "
                   "clearing was built round it.")
    else:
        t = h.get("title") or "<untitled>"
        src = (h.get("frame") or "").strip()
        if not src.startswith(framed_origins()):
            bad.append(f"the fire frames {src!r}, which is not an origin this site frames. "
                       "love-embed.js returns quietly for it, which is a button somebody "
                       "presses and presses.")
        if "list=" not in src:
            bad.append("the fire's frame carries no list id, so it is not the playlist it "
                       "says it is.")
        if h.get("length") or h.get("spoken") or h.get("runtime"):
            bad.append("the fire carries a runtime. Every recording at the fire must have one "
                       "and this must not: a playlist its channel keeps adding to has no "
                       "length, and today's total would be wrong next week while looking "
                       "authoritative. Say it runs until you stop it.")
        for field in ("title", "channel", "note", "playlist", "read"):
            if not (h.get(field) or "").strip():
                bad.append(f"the fire has no {field}.")
        if walled and (h.get("channel") or "").strip() == walled:
            bad.append(f"the fire is on {walled!r}, which this room refuses.")
        o = h.get("opens") or {}
        if not YT.match(o.get("id") or "") or not (o.get("title") or "").strip() \
                or not CLOCK.match((o.get("length") or "").strip()):
            bad.append("the fire does not say which video its playlist opens on, with that "
                       "video's id, title and runtime. Position 1 decides whether the whole "
                       "list embeds at all, and check-jukebox.py asks YouTube about it.")
        # THE FIRES IN THE PLAYLIST, a rack under the fire (rack.js's pattern).
        # Every one is a recording, so the runtime rule turns back over: each
        # needs one. They are the channel's, like the list, and our notes on
        # them say what is in the picture and nothing about what it is for.
        fires = h.get("fires") or []
        if not fires:
            bad.append("the fire has no rack of fires under it. The Campfire at Cavendish Coworking "
                       "reads its fires from here, and would have nothing on it.")
        seen_f = set()
        for f in fires:
            ft = f.get("title") or "<untitled>"
            if not YT.match(f.get("id") or ""):
                bad.append(f"the fire {ft!r} has {f.get('id')!r}, which is not a YouTube id.")
            if f.get("id") in seen_f:
                bad.append(f"the fire {ft!r} is in the rack twice.")
            seen_f.add(f.get("id"))
            if not CLOCK.match((f.get("length") or "").strip()) or not (f.get("spoken") or "").strip():
                bad.append(f"the fire {ft!r} has no runtime. It is one recording, and every "
                           "recording here says how long before the press.")
            if (f.get("channel") or "") != (h.get("channel") or ""):
                bad.append(f"the fire {ft!r} is on {f.get('channel')!r} and not the playlist's channel.")
            for field in ("title", "note", "measured"):
                if not (f.get(field) or "").strip():
                    bad.append(f"the fire {ft!r} has no {field}.")
            mf = FOR.search(f.get("note") or "")
            if mf:
                bad.append(f"the note on the fire {ft!r} says {mf.group(0)!r}. Say what is in the "
                           "picture, not what the fire is for.")
        m = FOR.search(h.get("note") or "")
        if m:
            bad.append(f"the fire's note says {m.group(0)!r}. The channel sells these fires for "
                       "sleep and focus and this room copies none of it: it does not treat a "
                       "meadow, or a fire, as a treatment. Say what is in the picture.")

    # The braid is somebody's teaching and the numbers are part of it.
    br = d.get("braid") or {}
    bundles = br.get("bundles") or []
    if len(bundles) != 3:
        bad.append(f"the braid has {len(bundles)} bundle(s). It is three: seven behind, "
                   "seven laws, seven ahead.")
    for b in bundles:
        n = len(b.get("strands") or [])
        if n != 7:
            bad.append(f"the braid's bundle {b.get('no')} has {n} strand(s) and not seven. "
                       "Twenty-one strands in three sevens is the teaching, not the layout.")
        if not (b.get("words") or "").strip():
            bad.append(f"the braid's bundle {b.get('no')} carries no words from the video.")
    if not YT.match((br.get("video") or "")):
        bad.append("the braid does not say which video it was transcribed from.")
    if not (br.get("speaker") or "").strip() or not (br.get("org") or "").strip():
        bad.append("the braid does not say who is speaking or where it was published. "
                   "An unattributed teaching is the one thing this site does not publish.")

    for q in d.get("quotes") or []:
        if not (q.get("text") or "").strip():
            bad.append(f"quote {q.get('key')!r} is empty.")
        if not (q.get("checked") or "").strip():
            bad.append(f"quote {q.get('key')!r} does not say what was checked about it. "
                       "Three of these are verbatim on our own pages and one is not; a "
                       "reader cannot tell which without being told.")

    bk = d.get("book") or {}
    if not (bk.get("borrow") or "").strip():
        bad.append("the book has no borrow link. Access is the point; buying is the "
                   "fallback — make-hermitage.py's rule, and this is the room that "
                   "cannot afford to break it.")

    g = d.get("grass") or {}
    src = (g.get("src") or "").strip()
    if not src.startswith(framed_origins()):
        bad.append(f"Ryan's video points at {src!r}, which is not an origin this site "
                   "frames. Add it to love-embed.js's ORIGINS and re-run make-csp.py; "
                   "this tool and the header both read that array.")
    if not CLOCK.match((g.get("length") or "").strip()):
        bad.append("Ryan's video has no runtime, and it is a press-to-play control like "
                   "every other one here.")
    if not (g.get("who") or "").strip():
        bad.append("Ryan's video names nobody. A video is credited like a voice is.")
    return bad


# ── The room ─────────────────────────────────────────────────────────────────

def screens(rows, cls):
    out = []
    for r in rows:
        out.append(
            f'      <li class="{cls}">\n'
            f'        <h3>{esc(r["title"])}</h3>\n'
            f'        <p class="swg-by">{esc(r["channel"])} &middot; {esc(r["length"])}</p>\n'
            f'        <p>{esc(r["note"])}</p>\n'
            f'        <button type="button" class="facade" data-embed-id="{esc(r["id"])}"\n'
            f'                data-embed-title="{html.escape(r["title"], quote=True)}">'
            f'Play &middot; {esc(r["spoken"])}</button>\n'
            f'      </li>')
    return "\n".join(out)


def hearth_block(h):
    # A LARGE PLATE, AND DRAWN IN THE ROOM'S OWN GOLDS. No poster: the fire's
    # real orange arrives only inside a frame somebody pressed for, so the page
    # is not made flame-lit by the back door (see §25). The plate is the width
    # of the clearing rather than one sit in the grid, because this is the fire
    # and the others are told round it.
    #
    # AND THE PLATE IS A SCREEN WITH A RACK UNDER IT, rack.js's pattern (Ryan's
    # call, 2026-09-28; the fire pit 2026-09-29): the fires in the playlist, each
    # playing where it stands or going up on the fire in place of the whole list,
    # and the way back puts the plate back without lighting it. The Campfire at
    # Cavendish Coworking reads the same fires from here. The rack is a <details>
    # that ships open, because a shut rack is text the render checkers cannot see.
    frame = h["frame"] + ("&" if "?" in h["frame"] else "?") + "autoplay=1"
    cards = []
    for f in h["fires"]:
        src = f'https://www.youtube-nocookie.com/embed/{f["id"]}?autoplay=1&rel=0'
        cards.append(
            f'          <li class="swg-sit" data-rack-card>\n'
            f'            <h3>{esc(f["title"])}</h3>\n'
            f'            <p class="swg-by">{esc(f["channel"])} &middot; {esc(f["length"])}</p>\n'
            f'            <p>{esc(f["note"])}</p>\n'
            f'            <button type="button" class="facade" data-embed-id="{esc(f["id"])}"\n'
            f'                    data-embed-title="{html.escape(f["title"], quote=True)}">'
            f'Play &middot; {esc(f["spoken"])}</button>\n'
            f'            <button type="button" class="swg-up" hidden data-rack-to="fire" data-rack-name="the fire" '
            f'data-rack-src="{html.escape(src, quote=True)}" '
            f'data-rack-title="{html.escape(f["title"], quote=True)}, {html.escape(f["channel"], quote=True)}, on the fire" '
            f'data-rack-film="{html.escape(f["title"], quote=True)}" data-rack-runtime="{esc(f["length"])}">'
            f'Put it on the fire &middot; {esc(f["spoken"])}</button>\n'
            f'          </li>')
    return (
        f'      <div class="swg-plot swg-hearth">\n'
        f'        <h3>The fire</h3>\n'
        f'        <p class="swg-by">{esc(h["channel"])} &middot; a playlist, so no runtime</p>\n'
        f'        <p>{esc(h["note"])}</p>\n'
        f'        <div class="swg-glass" data-rack-screen="fire" '
        f'data-rack-off="The whole playlist is off until you put it back.">\n'
        f'          <button type="button" class="facade" data-embed-src="{html.escape(frame, quote=True)}"\n'
        f'                  data-embed-title="{html.escape(h["title"], quote=True)}, on YouTube">'
        f'Light the fire &middot; runs until you stop it</button>\n'
        f'        </div>\n'
        f'        <p class="swg-now" data-rack-now="fire" tabindex="-1" hidden></p>\n'
        f'        <p class="swg-back" hidden><button type="button" class="swg-up" data-rack-back="fire">'
        f'Take it off and put the whole playlist back</button></p>\n'
        f'        <p class="swg-cap">No runtime on this one, and every other press in the clearing '
        f'has one: a playlist is a list its channel keeps adding to, and a total here would '
        f'be wrong the next time it changed. It is <a href="{esc(h["playlist"])}">'
        f'{esc(h["title"])}</a>, on YouTube, read on {esc(h["read"])}, and it starts at the top.</p>\n'
        f'        <details class="swg-fires" open>\n'
        f'          <summary>The fires in the playlist</summary>\n'
        f'          <p class="swg-cap">Some of the fires in it, each with how long it runs. Each one burns '
        f'where it stands, or goes up on the fire in place of the whole playlist. Their titles are the '
        f'channel&rsquo;s; the notes are ours.</p>\n'
        f'        <ul class="swg-sits">\n' + "\n".join(cards) + '\n        </ul>\n'
        f'        </details>\n'
        f'      </div>')


def preview_block(r):
    # ONE PRESS BESIDE THE BOOK, the start of the authorised audiobook in her own
    # voice. It is a store's preview, and the store's buy link is not repeated:
    # the way to the rest is the borrow link under it.
    return (f'      <div class="swg-listen">\n'
            f'        <h3>{esc(r["title"])}</h3>\n'
            f'        <p class="swg-by">{esc(r["channel"])} &middot; {esc(r["length"])}</p>\n'
            f'        <p>{esc(r["note"])}</p>\n'
            f'        <button type="button" class="facade" data-embed-id="{esc(r["id"])}"\n'
            f'                data-embed-title="{html.escape(r["title"], quote=True)}">'
            f'Play &middot; {esc(r["spoken"])}</button>\n'
            f'      </div>')


def braid_block(br):
    out = [f'      <p class="swg-braid-say">&ldquo;{esc(br["intro"])}&rdquo;</p>',
           '      <ol class="swg-bundles">']
    for b in br["bundles"]:
        strands = "".join(
            f'<li><span class="swg-strand-no">{i + 1}</span>{esc(s)}</li>'
            for i, s in enumerate(b["strands"]))
        out.append(
            f'        <li class="swg-bundle swg-bundle--{b["no"]}">\n'
            f'          <h3><span class="swg-seven">seven</span> {esc(b["gloss"])}</h3>\n'
            f'          <blockquote><p>{esc(b["words"])}</p></blockquote>\n'
            f'          <ul class="swg-strands">{strands}</ul>\n'
            f'        </li>')
    out.append('      </ol>')
    out.append(f'      <p class="swg-braid-say">&ldquo;{esc(br["close"])}&rdquo;</p>')
    out.append(f'      <p class="swg-braid-say swg-braid-say--root">&ldquo;{esc(br["roots"])}&rdquo;</p>')
    out.append(
        f'      <p class="swg-braid-who">Transcribed from <a href="https://www.youtube.com/watch?v='
        f'{esc(br["video"])}">Sweet Grass Teaching</a> at {esc(br["at"])}, published by '
        # An organisation whose name already ends in a full stop -- "Shawenim
        # Abinoojii Inc." -- came out with two of them. The sentence supplies
        # its own only when the name has not.
        f'{esc(br["org"])}{"" if br["org"].endswith(".") else "."} '
        f'<strong>The video does not name the Elder speaking</strong> &mdash; '
        f'not in the description, not on the channel, not at the end &mdash; so neither do we, '
        f'rather than guess at one. The words are the video&rsquo;s own captions, punctuated '
        f'and not otherwise changed; the timestamp is there so you can check them.</p>')
    return "\n".join(out)


def quote_block(q):
    if q.get("ours"):
        cite = (f'<p class="swg-q-ours">Also on our own <a href="{esc(q["ours"])}">'
                f'{esc(q["ours_title"])}</a>.</p>')
    else:
        cite = ('<p class="swg-q-ours">Not on any page of ours, and not confirmed against '
                'the book from here.</p>')
    return (f'      <figure class="swg-quote">\n'
            f'        <blockquote><p>{esc(q["text"])}</p></blockquote>\n'
            f'        <figcaption>Robin Wall Kimmerer, <cite>Braiding Sweetgrass</cite>'
            f'{cite}</figcaption>\n'
            f'      </figure>')


def grass_block(g, bk):
    # WRAPPED, BECAUSE A CLASS ON THE BUTTON DOES NOT SURVIVE THE PRESS.
    # love-embed.js replaces the <button> with a <div class="facade"> and that
    # is the whole class list -- anything the button was wearing is gone. This
    # clip is portrait and needs a 9/16 box, and a class on the button bought
    # nothing: the player came out 16/9 and letterboxed, which is the exact
    # thing the rule was written to prevent. The Pebble Board already solved
    # this by styling its pressed state from the CONTAINER (.pb-card .facade),
    # and this is the same answer.
    return (
        f'      <p class="swg-by">{esc(g["who"])} &middot; {esc(g["length"])} &middot; '
        f'already on our own <a href="{esc(g["ours"])}">{esc(g["ours_title"])}</a></p>\n'
        f'      <div class="swg-clip">\n'
        f'        <button type="button" class="facade" data-embed-src="{esc(g["src"])}"\n'
        f'                data-embed-title="{html.escape(g["title"], quote=True)}">'
        f'Play &middot; {esc(g["spoken"])}</button>\n'
        f'      </div>\n'
        f'      <p class="swg-cap">{esc(g["note"])}</p>')


def shelf_block(bk):
    return (f'      <p class="swg-book"><strong>{esc(bk["title"])}</strong><br>'
            f'{esc(bk["author"])} &middot; {esc(bk["publisher"])}</p>\n'
            f'      <p class="swg-go"><a href="{esc(bk["borrow"])}">Borrow it &rarr;</a> '
            f'&middot; <a href="{esc(bk["worldcat"])}">find a library copy</a></p>\n'
            f'      <p class="swg-cited">Quoted throughout, and already quoted on our own '
            f'<a href="{esc(bk["cited"])}">{esc(bk["cited_title"])}</a>.</p>')


# ── The credits ──────────────────────────────────────────────────────────────

def rows(items, kind):
    out = []
    for r in items:
        out.append(f'      <tr><td>{esc(r["title"])}</td><td>{esc(r["channel"])}</td>'
                   f'<td>{esc(r["length"])}</td><td>{kind}</td>'
                   f'<td><a href="https://www.youtube.com/watch?v={esc(r["id"])}">watch</a></td></tr>')
    return "\n".join(out)


def quote_rows(qs):
    out = []
    for q in qs:
        ours = (f'<a href="{esc(q["ours"])}">{esc(q["ours_title"])}</a>'
                if q.get("ours") else "&mdash;")
        out.append(f'      <tr><td>{esc(q["key"])}</td><td>{ours}</td>'
                   f'<td>{esc(q["checked"])}</td></tr>')
    return "\n".join(out)


def main():
    d = json.loads(DATA.read_text())
    bad = check(d)
    if bad:
        print("REFUSING to build Swaying Sweetgrass:")
        for b in bad:
            print("  - " + b)
        return 1

    page = ROOM.read_text()
    for js in ("love-embed.js", "rack.js"):
        if f'<script src="{js}" defer></script>' not in page:
            print(f"REFUSING to build Swaying Sweetgrass: {ROOM.name} does not load {js}, so the "
                  "fire's rack would press and do nothing.")
            return 1
    swap(ROOM, "sweetgrass-hearth", hearth_block(d["hearth"]), "    ")
    swap(ROOM, "sweetgrass-fire", screens(d["fire"], "swg-sit"), "    ")
    swap(ROOM, "sweetgrass-preview", preview_block(d["book"]["preview"]), "    ")
    swap(ROOM, "sweetgrass-guide", screens(d["teachings"], "swg-teach"), "    ")
    swap(ROOM, "sweetgrass-braid", braid_block(d["braid"]), "    ")
    swap(ROOM, "sweetgrass-grass", grass_block(d["grass"], d["book"]), "    ")
    swap(ROOM, "sweetgrass-shelf", shelf_block(d["book"]), "    ")
    for q in d["quotes"]:
        swap(ROOM, f"sweetgrass-quote-{q['key']}", quote_block(q), "    ")

    h = d["hearth"]
    swap(NOTES, "sweetgrass-hearth-credits",
         f'      <tr><td>{esc(h["title"])}</td><td>{esc(h["channel"])}</td>'
         f'<td>no runtime</td><td>a playlist, a screen</td>'
         f'<td><a href="{esc(h["playlist"])}">watch</a></td></tr>', "      ")
    swap(NOTES, "sweetgrass-fire-credits", rows(d["fire"] + h["fires"], "a screen"), "      ")
    swap(NOTES, "sweetgrass-preview-credits", rows([d["book"]["preview"]], "a screen"), "      ")
    swap(NOTES, "sweetgrass-guide-credits", rows(d["teachings"], "a screen"), "      ")
    swap(NOTES, "sweetgrass-quote-credits", quote_rows(d["quotes"]), "      ")

    print(f"sweetgrass: a playlist of real fires in the pit with no runtime, "
          f"{len(d['fire'])} recordings at the fire, the audiobook's preview beside the book, "
          f"{len(d['teachings'])} teachings in the field guide, "
          f"{len(d['braid']['bundles'])} bundles of seven in the braid, "
          f"{len(d['quotes'])} passages, credits rebuilt.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
