#!/usr/bin/env python3
"""Read every feed on the board and write what is on them into data/arrivals.json.

THIS IS THE ONLY TOOL HERE THAT TOUCHES THE NETWORK, and it is kept out of the
pre-deploy sequence for check-jukebox.py's reason: a build that cannot run on a
train is a build that stops being run. `make-arrivals.py` draws the board out of
the file this writes and needs nothing but the file.

WHY THE BOARD IS A SNAPSHOT AND SAYS SO. An RSS feed cannot be read from the
page: none of these hosts sends an Access-Control-Allow-Origin header, so a
browser refuses the fetch, and the only ways round it are a proxy we do not run
or a third-party reader we would be handing our visitors to. So the board is set
at build time by somebody running this. THAT IS NOT A LIMITATION THE ROOM HIDES
-- it is the whole design. A split-flap board in a station is set by a machine
somebody switched on; it is a picture of the railway and not the railway, and it
carries the time it was set so that nobody mistakes one for the other. This is
make-jungle.py's refused runtime standing on its head: a live camera has no
length to give, so publishing one would be a number that goes quietly wrong,
and a board HAS a time it was set, so refusing to publish that would be the
same fault upside down. Every wire below records the minute it was read.

WHAT IT TAKES OFF EACH ITEM: the title, the link, and the date. Nothing else.
Not the description, not the content, not the author, not the categories. A
departures board gives you a name and a time; it does not read you the contents
of the train. That is the room's argument and it is also what keeps this page
from quietly republishing everybody else's writing onto one surface -- and it is why
`make-arrivals.py` REFUSES an item carrying a summary field. The friendly edit
is a real one and it will arrive: the rows look bare, somebody pastes the
excerpts back in, and the board becomes a reader.

WHAT IT REFUSES, and why each one is here:

  · A FEED THAT DID NOT ANSWER 200, or that is not RSS 2.0. Every one of these
    files is generated by a sibling repository, so a format change is news
    rather than something to paper over. Atom is deliberately NOT parsed: a
    silent mis-parse would put a half-empty board on the street, and a refusal
    the day a sibling switches is the thing worth having.

  · AN ITEM WITH NO DATE. The board sorts on the date and prints it on the row.
    A row with no time on it is the one thing an arrivals board cannot show.

  · AN ITEM WHOSE LINK IS NOT ON THAT WIRE'S OWN HOST. make-hermitage.py's rule
    about the Star Stuff bench: a rack with somebody's name on it holding
    something else is a mis-filed thing that reads as a claim. A syndicated
    item pointing off-site would be this board telling a visitor that Penguin
    Pebbling published something it did not.

  · A TITLE WITH MARKUP LEFT IN IT. make-toys.py's lesson about entities in a
    payload: the board writes these with textContent semantics in mind, so a
    stray tag or a raw entity arrives on the page as literal characters.

IT DOES NOT INVENT A WIRE. The `wires` list is hand-kept -- which site, which
feed of that site, and our own one-line note about what the feed is for. Picking
a feed is a curation decision and it belongs to a person: starstuff.earth and
queering.earth each publish two, and choosing silently between them would make
the board say "the latest from Star Stuff" while hiding which Star Stuff it
meant. Each wire names its feed on the page and links it.
"""
import email.utils
import json
import re
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "arrivals.json"

# How many rows a board holds. Six is a board: enough that a wire looks like it
# has a history, few enough that a hall of them is still a page somebody reads
# rather than scrolls past. The number is never typed into the room -- the page
# says how many it is showing by counting what it drew.
ROWS = 6

UA = "Stimpunks.Love arrivals board (+https://stimpunks.love/the-feed.html)"

TAG = re.compile(r"<[^>]+>")
ENTITY = re.compile(r"&(?:#\d+|#x[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]+);")


def die(msg):
    raise SystemExit(f"REFUSING: {msg}")


def fetch(url):
    req = urllib.request.Request(url, headers={
        "User-Agent": UA,
        "Accept": "application/rss+xml, application/xml, text/xml",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            if r.status != 200:
                die(f"{url} answered {r.status}.")
            return r.read()
    except urllib.error.HTTPError as e:
        die(f"{url} answered {e.code}.")
    except Exception as e:
        die(f"{url} could not be read: {e}")


def same_host(link, host):
    """The link's host is the wire's host, or a subdomain of it."""
    h = (urlparse(link).hostname or "").lower().removeprefix("www.")
    host = host.lower().removeprefix("www.")
    return h == host or h.endswith("." + host)


def parse(xml, wire):
    try:
        root = ET.fromstring(xml)
    except ET.ParseError as e:
        die(f"{wire['feed']} is not parseable XML: {e}")
    if root.tag != "rss":
        die(
            f"{wire['feed']} is <{root.tag}> and not RSS 2.0.\n"
            "Atom is not parsed here on purpose -- see the note at the top. If a "
            "sibling has\nswitched format, teach this tool the new one "
            "deliberately rather than guessing at it."
        )
    channel = root.find("channel")
    if channel is None:
        die(f"{wire['feed']} is RSS with no <channel> in it.")

    out = []
    for item in channel.findall("item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        when = (item.findtext("pubDate") or "").strip()
        if not title:
            die(f"{wire['feed']} has an item with no title.")
        if TAG.search(title) or ENTITY.search(title):
            die(
                f"{wire['feed']}: this title still has markup in it and would reach "
                f"the page as literal characters:\n  {title}"
            )
        if not link:
            die(f"{wire['feed']}: {title!r} has no link.")
        if not when:
            die(
                f"{wire['feed']}: {title!r} has no pubDate.\nThe board sorts on the "
                "date and prints it on the row; a row with no time on it is the one "
                "thing\nan arrivals board cannot show."
            )
        if not same_host(link, wire["host"]):
            die(
                f"{wire['feed']}: {title!r} links to {urlparse(link).hostname}, which "
                f"is not {wire['host']}.\nA rack with somebody's name on it holding "
                "something else is a mis-filed thing that reads\nas a claim -- "
                "make-hermitage.py's rule about the Star Stuff bench."
            )
        try:
            dt = email.utils.parsedate_to_datetime(when)
        except (TypeError, ValueError) as e:
            die(f"{wire['feed']}: {title!r} has an unreadable pubDate {when!r}: {e}")
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        out.append({
            "title": title,
            "url": link,
            "date": dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        })

    if not out:
        die(f"{wire['feed']} answered 200 with no items in it.")
    # SORTED HERE rather than trusted: the Doomscroll's rule. A feed is supposed
    # to be newest-first, and a generator per wire is a chance per wire for one not to be.
    out.sort(key=lambda i: i["date"], reverse=True)
    return out[:ROWS]


def main():
    data = json.loads(DATA.read_text())
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")

    for wire in data["wires"]:
        for k in ("id", "site", "host", "feed", "feed_name", "note"):
            if not wire.get(k):
                die(f"a wire is missing {k}: {wire.get('id') or wire}")
        items = parse(fetch(wire["feed"]), wire)
        wire["items"] = items
        wire["read"] = now
        print(f"  {wire['site']:<34} {len(items)} rows, newest {items[0]['date'][:10]}")

    data["set"] = now
    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"\nWrote {DATA.relative_to(ROOT)} — board set at {now}.")
    print("Now run tools/make-arrivals.py to set the board itself.")


if __name__ == "__main__":
    sys.exit(main())
